---
title: "OfficeR Plot Generation"
author: "Andrew Zhang"
date: "11/12/2018"
output: pdf_document
---

```{r}
install.packages("officer")
library(officer)
library(magrittr)
library(tidyverse)
library(readxl)

##  pic a template you like
pres1 <- read_pptx("blank.pptx") 


##  get the layout
layout_summary(pres1)

master <- "Office Theme"
```

```{r}
layout_properties(x = pres1, layout = "Title and Content", master = master )

## make a slide

pres1 %<>% 
  add_slide(layout = "Title and Content",
            master = master) %>% 
  ph_empty(type = 'title') %>%
  ph_add_fpar(fpar(ftext('the last Bear Market',
                         prop = fp_text(font.family = 'Arial (Headings)', 
                                        font.size = 44))), 
              type = 'title') %>%
  ph_with_ul(type="body", 
             str_list = c("Sept. 30, 2002 Dow 7528", 
                          "Jan. 5, 2004 Dow 10,568", 
                          "Oct. 8, 2007 Dow 14093"), 
             level_list = c(1, 1, 1), 
             style = fp_text(font.size = 36, font.family = "Arial", bold = TRUE)) 

pres1 %<>% 
  add_slide(layout = "Title and Content",
            master = master) %>% 
    ph_empty(type = 'title') %>%
  ph_add_fpar(fpar(ftext('What I do in a Bear Market',
                         prop = fp_text(font.family = 'Arial (Headings)', 
                                        font.size = 44))), 
              type = 'title') %>%
  ph_with_ul(type="body", 
             str_list =  c("Decide whether this is a market correction or the start of something more", 
                           "Review the stocks you own",
                           "Review stocks you wanted to own but were too expensive at time of research", 
                           "Check your portfolio for balance or the type of stocks you own"),
             level_list = c(1, 1, 1, 1),
             style = fp_text(font.size = 36, font.family = "Arial", bold = TRUE))

print(pres1, target = "Bear7_8.pptx") 


```